### ISSUE TITLE
Re-init doesn't seem to properly reset :(

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar#109]
If I add some warriors a run, initialising again doesn't seem to properly reset anything?

**Comment by gareththegeek** [comment]
Do you think this is a bug in the core library?  Thinking about it, I may not have intentionally written it to be re-runnable...
I'll add it to ze board!

**Comment by gareththegeek** [comment]
Seems like this already done :shipit:

**Comment by dougajmcdonald** [comment]
Fixed in #110
