### ISSUE TITLE
WinnerId not always returned

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar#111]
Sometimes the status bar shows `Simulation complete - win` without a winnerId.

The UI code says:

```
  if(roundResult.outcome) {
    let outcome = `simulation complete - ${roundResult.outcome}`;
    if(roundResult.winnerId) {
      outcome += ` - winner id: ${roundResult.winnerId}`
    }
    return outcome;
  }
```

So for me, it seems like the core isn't generating a winnerId sometimes

**Comment by gareththegeek** [comment]
You're Winner!!

**Comment by gareththegeek** [comment]
This is an issue in the UI project - 0 is falsey
