### ISSUE TITLE
When more than two warriors in the core, the end condition doesn't prevent fetcher from calling fetch on a dead warrior (one with no tasks)

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar#124]
The latest changes seem to crash more easily that before, looked into things by hitting a debugger in `fetcher.fetch` these two line have me stumped:

```
            state.warriorIndex = (wi + 1) % state.warriors.length;
            warrior.taskIndex = (ti + 1) % warrior.tasks.length;
```

Firstly, they both alter existing state stuff which I think it bad practice, but that aside what's the `% .length` for? isn't this just supposed to go to the next instruction?
**EDIT:** 
I think i figured it out, the mod is for the wrapping right?

Well, I managed to catch the error and basically it happens when `warrior.tasks.length === 0` then it tries to do `ti + 1 % warrior.tasks.length` resulting, in my example in 1 % 0 giving a `NaN` and blowing up.

This is what I logged as I didn't trust the changes to objects.

```
            console.log('wi before', state.warriorIndex)
            state.warriorIndex = (wi + 1) % state.warriors.length;
            console.log('wi after', state.warriorIndex)
            console.log('taskIndex before', warrior.taskIndex)
            warrior.taskIndex = (ti + 1) % warrior.tasks.length;
            console.log('taskIndex after', warrior.taskIndex)

            var ip = task.instructionPointer;
            var instruction = core.executeAt(task, ip);

            console.log('instructionPointer before', task.instructionPointer)
            task.instructionPointer = (ip + 1) % state.options.coresize;
            console.log('instructionPointer after', task.instructionPointer)
```

I wrapped it all in the try / catch with a debugger in the catch and this was the last run of the `console.log`

```
wi before 0
wi after 1
taskIndex before 0
taskIndex after NaN
```

As you said before the issues comes as the warrior denoted basically comes into `fetch` with no tasks.

**EDIT2**
I logged the live warriors from the `check` in end condition before the error and for a core with 3 warriors there are only 2 live before going from `endCondition` > `fetcher.fetch` looks like it occurs when  a warrior is killed but it's not an endgame (my examples are triggering when I have 3 warriors, will try with two and report back.
```
        const liveWarriors = state.warriors.filter((warrior: IWarrior) => warrior.tasks.length > 0);
        console.log('liveWarriors', liveWarriors.length)
-
liveWarriors 2
liveWarriors 2
wi before 0
wi after 1
taskIndex before 0
taskIndex after NaN
```

**EDIT3:**
yeah, 2 works fine, need to establish what should happen inside `fetcher.fetch` when the warrior index is a warrior which was just killed. I tried to just skip it but couldn't get it work as I guess we need to return something meaningful as the `context` didn't know if we could just return nothing, or return the values from the next warrior or what.

**Comment by gareththegeek** [comment]
Sounds like it just shouldn't be interacting with dead warriors?

**Comment by dougajmcdonald** [comment]
That was my thought but what should fetch return in that case?
