### ISSUE TITLE
Hang condition

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar#131]
I'm seeing some rounds where the core never sends the round end event and stops sending the run progress event too leaving the UI in a perma running state. This is a sporadic issue, sometimes it completes, sometimes it doesn't. 

There is no crash or console errors, just a weird hung state.

![image](https://user-images.githubusercontent.com/1190042/34412382-d261c232-ebd4-11e7-9e33-50a168da9a9d.png)

Used the following two warriors:

Stone:

```
       step   equ 1185           ; mod 5

inc     spl    #-step,   <step
stone   mov    >step,    1-step
        sub    inc,      stone
        djn.f  stone,    <5555
```

Paper:

```
        step   equ 5620

paper   mov    #5,       #0
copy    mov    <paper,   {dest
        jmn    copy,     paper
        spl    >paper,   {-1277
dest    jmz    step,     *0
```

Only thing I can think of at the moment is perhaps a standard conflict.

**Comment by gareththegeek** [comment]
Shouldn't be a standards problem, these are both 94nop compliant

**Comment by gareththegeek** [comment]
Is this resolved now?

**Comment by dougajmcdonald** [comment]
Probably!
