### ISSUE TITLE
Function which triggers resending of core access events

### ISSUE THREAD

**Issue by gareththegeek** [gareththegeek/corewar#155]
In order to support mobile devices in [corewar-ui](https://github.com/gareththegeek/corewar-ui) it is necessary to allow apps to request a resending of all core access messages when, for example, screen orientation changes.

When requested the most recent core access event in the round for each core address should be republished using the pub sub mechanism.

**Comment by dougajmcdonald** [comment]
Also, ideally the publishing of the events should be batched so there is only a single `pubsub.publish()`

**Comment by gareththegeek** [comment]
On it
