### ISSUE TITLE
Allow initialise with zero parse results

### ISSUE THREAD

**Issue by gareththegeek** [gareththegeek/corewar#179]
The library should not error if an empty array of `IParseResult` is handed to the initialise function.

The initialise message should be published as normal.

**Comment by gareththegeek** [comment]
Do you have the error deets, or is there a way to reproduce this from the UI project?

The corewar library specifically unit tests for empty warrior array passed into `initialise` and I am not seeing anything obvious that would cause the error.

**Comment by dougajmcdonald** [comment]
This is fixed by some UI bits and bobs, it was the UI breaking not the core
