### ISSUE TITLE
Error running tests

### ISSUE THREAD

**Issue by gareththegeek** [gareththegeek/corewar#20]
If I run tests with `npm test` I get the following error: Unable to compile typescript
Main app is working now though on the plus side...
![image](https://user-images.githubusercontent.com/6231841/32857067-961aede2-ca3e-11e7-89b2-aa02bf010b14.png)

**Comment by dougajmcdonald** [comment]
Seriously WTF, I just deleted the folder, cloned the repo again, `npm i` > `npm test` and all 503 passed :/ I'm at a loss

**Comment by gareththegeek** [comment]
I did an `npm -install` and I still get the same result - am I missing something?

![image](https://user-images.githubusercontent.com/6231841/32911353-d8264b8a-cb03-11e7-87e6-4fa73377820a.png)

**Comment by dougajmcdonald** [comment]
aha, that's a different error and I think I'm beginning to understand the cause. 

When I add in a `tsconfig.json` I'm asked to specify a target for the `.ts` compilation, es3, es5 etc. if I target es5 I get the error you're seeing. If I target es2017 for example it goes away...but the matcher thing still buggers up.

I'm going to PR with the matcher tests excludes and a `tsconfig.json` targetting es2017

**Comment by dougajmcdonald** [comment]
@gareththegeek Can you delete the folder and re-clone, switching to master etc and pulling won't cull everything _enough_ 

Also, what version of node and npm are you on?

**Comment by gareththegeek** [comment]
Running `npm install -g npm` and `git pull` seems to have sorted this out, I now have a working test  runner
