### ISSUE TITLE
Where shall we create the UI project?

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar#22]
I want to test the UI project can consume this one via NPM, I'm not sure I can create a repo under your account though.

Want me to create it under mine and link them (somehow?) or I can create it under the organisation?

https://github.com/orgs/compu-global-hyper-meganet/dashboard

**Comment by dougajmcdonald** [comment]
Thinking about it, I can probably just test locally in the short term.

**Comment by gareththegeek** [comment]
I have created a repo and added you as a collaborator https://github.com/gareththegeek/corewar-ui
