### ISSUE TITLE
Competitors

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar#28]
This came up when I searched for corewar on NPM:

https://www.npmjs.com/package/phl0cks

Good news is the download numbers, and that there was only ONE matching result other than ours!

Time to "buy him out"

![buy him out](https://user-images.githubusercontent.com/1190042/32947541-05d0b85a-cb94-11e7-960f-74b886709109.jpg)

**Comment by gareththegeek** [comment]
I didn't get rich by writing a bunch of cheques!
