### ISSUE TITLE
Private warrior repository

### ISSUE THREAD

**Issue by gareththegeek** [gareththegeek/corewar#33]
We should allow users who have signed up to store their warriors privately on the site.

This would allow users to maintain and develop their own collection of warriors without disclosing the source code to rivals!

**Comment by dougajmcdonald** [comment]
definitely! Maybe we should 'sell' warriors? or allow people to? so you can have, some templates for free, but have to buy more complex warriors? I guess it wouldn't work seeing as how it's been out for ages and freely available, but not everyone knows that! :P

**Comment by gareththegeek** [comment]
Belongs in UI / Server project
