### ISSUE TITLE
Allow unit tests to be debugged

### ISSUE THREAD

**Issue by gareththegeek** [gareththegeek/corewar#60]
It is not currently possible to debug unit tests.  As the UI is now separated from this library it is only possible to perform poor man's debugging using console.logs!

**Comment by gareththegeek** [comment]
https://github.com/TypeStrong/ts-node/issues/46#issuecomment-296895962

**Comment by dougajmcdonald** [comment]
https://code.visualstudio.com/docs/editor/debugging

**Comment by gareththegeek** [comment]
I have debugging working with mocha, chai, sinon and sinon-chai!  Currently porting tests across on the `mocha-chai-sinon` branch

**Comment by dougajmcdonald** [comment]
Shit son! That's awesome!

**Comment by gareththegeek** [comment]
#72

**Comment by dougajmcdonald** [comment]
Close with #72?
