### ISSUE TITLE
Decide on final location and impl of pubsub'esque messages

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar#69]
I shoehorned in a pubsub for the core corewar package. We should decide if this is to take the place of the existing event system and give it a clean up.

I've needed to publish methods from two places inside this repo so have now had to dupe the code. Again, i'd like to clean this up once we have agreed how to go forward.

**Comment by gareththegeek** [comment]
Yep, keep the pubsub and remove the legacy EventLite bits

**Comment by gareththegeek** [comment]
Resolved by #95
