### ISSUE TITLE
Progress report when calling 'run()'

### ISSUE THREAD

**Issue by dougajmcdonald** [gareththegeek/corewar#70]
At the moment there is no progress update when 'run()' is called till the end of a match. It'd be nice if we could give some kind of update as to the number of cycles which have completed.

Additionally we may want to have the simulator batch core access updates so that we don't get 80000 one by one for performance reasons.

**Comment by gareththegeek** [comment]
Currently, the UI is controlling the number of steps per second by repeatedly calling step within `setInterval`.  It might be nice to allow a number of steps to be passed to the step function (defaulting to 1).  If multiple steps are requested it executes them all as quickly as possible, generating the minimum number of required messages.

However, I think this is probably one for the future as I'm not sure how much performance gain this would really achieve...

**Comment by gareththegeek** [comment]
This is superceded by #89.  I will raise a new issue for the residual - 

> Additionally we may want to have the simulator batch core access updates so that we don't get 80000 one by one for performance reasons.
