### ISSUE TITLE
Multi-step simulator function

### ISSUE THREAD

**Issue by gareththegeek** [gareththegeek/corewar#90]
Created from #70

> we may want to have the simulator batch core access updates so that we don't get 80000 one by one for performance reasons.

> Currently, the UI is controlling the number of steps per second by repeatedly calling step within setInterval. It might be nice to allow a number of steps to be passed to the step function (defaulting to 1). If multiple steps are requested it executes them all as quickly as possible, generating the minimum number of required messages.

> However,  I think this is probably one for the future as I'm not sure how much performance gain this would really achieve...

**Comment by dougajmcdonald** [comment]
That's not a bad idea as that's basically what I'm doing on the UI side atm anyway.
